/**
 * Generates apps/web/.env.local from your sncast accounts file, so the web
 * app's Settings open with the dev signer prefilled (fields only — you still
 * review and Save).
 *
 *   pnpm run web:devenv [account-name]     # default: deployer
 *
 * SAFETY: .env.local is git-ignored and must stay so. Vite bakes VITE_* values
 * into any bundle it builds — never point this at a key that holds real value,
 * and never commit the file.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const name = process.argv[2] ?? "deployer";
const accountsPath = join(homedir(), ".starknet_accounts", "starknet_open_zeppelin_accounts.json");
const accounts = JSON.parse(readFileSync(accountsPath, "utf8"));

let found = null;
for (const network of Object.values(accounts)) {
  if (network[name]) found = network[name];
}
if (!found) {
  console.error(`no account "${name}" in ${accountsPath}`);
  process.exit(1);
}

const out = `# generated by scripts/gen-web-env.mjs — git-ignored, testnet keys only
VITE_DEV_SIGNER_ADDRESS=${found.address}
VITE_DEV_SIGNER_KEY=${found.private_key}
`;
const target = join(dirname(fileURLToPath(import.meta.url)), "../apps/web/.env.local");
writeFileSync(target, out);
console.log(`wrote apps/web/.env.local (signer: ${name} ${found.address.slice(0, 10)}…)`);
console.log("restart the dev server to pick it up; Settings → Direct will open prefilled.");
